---
# tasks file for docker
- name: Add the group 'docker'
  group:
    name: docker
    state: present
    system: True

- name: Add the user 'docker'
  user:
    name: docker
    comment: docker service account
    shell: /sbin/nologin
    system: True
    group: docker

- name: Set OS dependent variables
  include_vars: '{{ DOWNLOAD_WAY }}.yml'

- name: Download binary
  get_url:
    url: "{{ download_url }}"
    dest: "/usr/local/src/docker-{{ DOCKER_VERSION }}.tgz"
    force: true
    mode: 0644
    owner: root
    group: root
    url_password: "{{ NEXUS_HTTP_USERNAME }}"
    url_username: "{{ NEXUS_HTTP_PASSWORD }}"
    timeout: 3
  register: docker_pkg1
  until: docker_pkg1 is succeeded
  retries: 10

- name: Extract docker
  unarchive:
    src: "/usr/local/src/docker-{{ DOCKER_VERSION }}.tgz"
    dest: /usr/local/bin
    remote_src: yes
    extra_opts:
      - --strip-components=1
  register: docker_pkg2

- name: Create data directory
  file: 
    name: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - /etc/docker
    - '{{ kubernetes.docker.datadir }}'

- name: Configuration daemon
  template: 
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  register: docker_conf

- name: Create a docker primary partition
  community.general.filesystem: 
    fstype: xfs
    dev: '{{ kubernetes.docker.device }}'
    state: present
  when: kubernetes.docker.device is defined

- name: Mount docker root dir
  ansible.posix.mount:
    src: '{{ kubernetes.docker.device }}'
    path: /var/lib/docker
    fstype: xfs
    opts: noatime
    state: present

- name: Install systemd file
  template: 
    src: docker.service.j2
    dest: /etc/systemd/system/docker.service
  register: docker_systemd

- name: Start the service
  systemd:
    name: docker
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: docker_pkg1.changed or docker_pkg2.changed or docker_conf.changed or docker_systemd.changed

- name: Install docker completion
  get_url: 
    url: https://raw.githubusercontent.com/docker/cli/master/contrib/completion/bash/docker
    dest: /etc/bash_completion.d/docker
    mode: 0755
    timeout: 3
  ignore_errors: True